### ISSUE TITLE
[Bug] Game window display nothing sometime

### ISSUE THREAD

**Issue by viet-hoang-96** [indigames/igeCreator#111]
I've to restart the app so it can work again. It happend after I used the editor (Edit > Play > Stop > Edit >...) for a while.

**Comment by viet-hoang-96** [comment]
![image](https://user-images.githubusercontent.com/52899605/135386670-8da7552d-bb6d-408a-93ae-5ec0437187b0.png)

**Comment by thai-phi** [comment]
Fixed in Build N#79
