### ISSUE TITLE
[Bug] Failed to display a mesh behind a mesh that has alpha channel on texture

### ISSUE THREAD

**Issue by viet-hoang-96** [indigames/igeCreator#114]

**Comment by viet-hoang-96** [comment]
![image](https://user-images.githubusercontent.com/52899605/135403148-6efcc304-8e95-46a0-832c-798d8f0db54b.png)

**Comment by viet-hoang-96** [comment]
![image](https://user-images.githubusercontent.com/52899605/135403217-9e69ec8b-ba01-46e8-86fb-5d2609b8a0b2.png)
![image](https://user-images.githubusercontent.com/52899605/135403259-68e52375-6d71-43ae-aa17-ebbfb232cf32.png)

**Comment by viet-hoang-96** [comment]
Model
https://drive.google.com/file/d/1MEW0A-g0_fgjXC7gCvbM-rLGMKgkX1-X/view?usp=sharing

**Comment by viet-hoang-96** [comment]
It's also happend with sprite that have alpha
![image](https://user-images.githubusercontent.com/52899605/135431748-46693016-cbdf-479a-b4ca-4efaad5250ba.png)

**Comment by saruyamatarou** [comment]
I think it can be fixed by updating pyxCore to the latest version and converting the data again.

**Comment by saruyamatarou** [comment]
![Untitled-1](https://user-images.githubusercontent.com/39523520/136320670-f47b7169-6817-4040-9945-52d45d904002.png)

**Comment by saruyamatarou** [comment]
@viet-hoang-96 
How about that?

**Comment by thai-phi** [comment]
Fixed in build#137, need to reconvert fbx model
