### ISSUE TITLE
[Bug] When disable the UI element the child is not disabled and disabled element still show in middle of edit scene

### ISSUE THREAD

**Issue by viet-hoang-96** [indigames/igeCreator#115]

**Comment by viet-hoang-96** [comment]
![image](https://user-images.githubusercontent.com/52899605/135558538-88c8fdc7-ba9b-4a07-82ab-5b1a344438e4.png)

**Comment by viet-hoang-96** [comment]
![image](https://user-images.githubusercontent.com/52899605/135558579-e634db7a-2321-4ee4-a765-077bcc1d958a.png)

**Comment by thai-phi** [comment]
Build No#76
