### ISSUE TITLE
[Request Feature] Script can use vec2, vec3 as variable

### ISSUE THREAD

**Issue by viet-hoang-96** [indigames/igeCreator#117]

**Comment by thai-phi** [comment]
Script can load prefab using scene instance, by calling scene.createObjectFromPrefab().
Scene instance can be obtained in serveral ways:
 - SceneManager.currentScene
 - self.owner.scene
 - from any SceneObject instance, using .scene

Serialize Vec2, Vec3, Vec4, Mat<N> will be added once have time.

**Comment by thai-phi** [comment]
Fixed with build#128.
Editor now can inspect Vec2, Vec3, Vec4 and Quat values from script.
