### ISSUE TITLE
[Bug] If scripts don't have onStart, onUpdate not running

### ISSUE THREAD

**Issue by viet-hoang-96** [indigames/igeCreator#125]

**Comment by viet-hoang-96** [comment]
![image](https://user-images.githubusercontent.com/52899605/135598069-253fa75e-15ca-4148-9ff7-d921f8bf22ee.png)

**Comment by thai-phi** [comment]
Scripts without 'onStart()' work now, but 'onUpdate' is mandatory for all script. If you don't have update function, just put a dummy function there.
