### ISSUE TITLE
[Bug] Some model cannot be select on editor but have to select using browse button

### ISSUE THREAD

**Issue by viet-hoang-96** [indigames/igeCreator#132]

**Comment by viet-hoang-96** [comment]
![image](https://user-images.githubusercontent.com/52899605/136007187-d19df847-67ea-470e-a214-408969cf42f4.png)
![image](https://user-images.githubusercontent.com/52899605/136007928-9c42a8a3-14ae-4aed-9bdc-689833e2e7c7.png)
The selectable one is animation fbx file

**Comment by viet-hoang-96** [comment]
https://drive.google.com/file/d/1VDEXyJ0K3tkUE-7C-1VgyqaM14zG6hzC/view?usp=sharing

**Comment by thai-phi** [comment]
Fixed with build N#85
