### ISSUE TITLE
[Feature request] Assigning editable figures back to Figure component

### ISSUE THREAD

**Issue by ducpham-indi** [indigames/igeCreator#166]
- Able to reassign editable figure back to the figure of the component
- The editable figure should be able to sync transform with the gameobject
- The editable figure should be able to replace immediately the old figure on the display
- When the scene reset, it should go back to the original figure before the assigning

**Comment by thai-phi** [comment]
TODO: implement EditableFigureComponent

**Comment by thai-phi** [comment]
Implemented in Build#150.

To assign an eFig back to a component, use EditableFigureComponent. The usage is just similar with FigureComponent, just the fact that it accepts EditableFigure to be assign back to the component.

Please check API usage in API Document.
