### ISSUE TITLE
[Feature request] Auto set sprite size to match the size of input file

### ISSUE THREAD

**Issue by ducpham-indi** [indigames/igeCreator#167]
Add a button to the sprite component to auto adjust sprite size to match with the current image size.
For example, the image size is: 300 x 200 pixel, the size of the sprite should be set to 3x2.

**Comment by thai-phi** [comment]
Added in build#145.
If the size set to (0, 0), it will auto take the texture size once loaded.
So, just set size to (0, 0) then setPath/setTexture it will always take the new size.
