### ISSUE TITLE
[Feature request] Enable adding multiple script components to an objects + tracking script component by script name

### ISSUE THREAD

**Issue by ducpham-indi** [indigames/igeCreator#172]
Able to use multiple script component, also the component should be tracked by the script name instead of using the name "Script"

**Comment by thai-phi** [comment]
Added in build#184.

To obtain the Script instance, use:
- SceneObject.getScript(): return the first attached script.
- SceneObject.getScript(name_or_path: string): return the attached script with specified path or name.
