### ISSUE TITLE
[Bug] Particle not showing on current scene, crash if create a new scene and add paritcle

### ISSUE THREAD

**Issue by viet-hoang-96** [indigames/igeCreator#176]
efk was exported using Effekseer tool ver 1.60e (1.53e also not working)
In current scene, I can see test.efk display but kira.efk is not, when play test.efk texture is missing
When I create new scene to test, both file cause editor crash
[effects.zip](https://github.com/indigames/igeCreator/files/7465908/effects.zip)

**Comment by thai-phi** [comment]
Fixed in build#160.
