### ISSUE TITLE
[Bug] Crash when use Ctrl to multiple select on hierarchy (only on specific 2 object)

### ISSUE THREAD

**Issue by viet-hoang-96** [indigames/igeCreator#183]
It's alway crash when I use Ctrl to select Basket1 and Basket2 on SuperMarket project
![image](https://user-images.githubusercontent.com/52899605/141745677-02a2b914-4c78-4724-9167-cb35a64055b6.png)

**Comment by thai-phi** [comment]
Not happened in build#184.
