### ISSUE TITLE
[Bug] Sprite UV is different between PC vs Mobile version

### ISSUE THREAD

**Issue by ducpham-indi** [indigames/igeCreator#208]
PC sprite

![image (11)](https://user-images.githubusercontent.com/56010272/145925249-7096efa4-c844-47e0-bb36-c3b17e70a6ac.png)

Mobile sprite

![6b8dcdc0-edbe-4e46-8656-c434d89585cf](https://user-images.githubusercontent.com/56010272/145925280-b3e9195b-a755-438c-832a-8398457f9d53.jpg)

**Comment by thai-phi** [comment]
This is not an issue with the editor, this is because of game bug.
