### ISSUE TITLE
[Bug] Model path in figure component cause clash if using backslash

### ISSUE THREAD

**Issue by ducpham-indi** [indigames/igeCreator#209]
`figures/corgi/Corgi_Run.fbx` works fine

`figures\\corgi\\Corgi_Run.fbx` cause crash on device when component is enabled.
There should be a form of error handling or converting from escaped backslash to forward slash.

**Comment by thai-phi** [comment]
Fixed in build#232.
Using Drag&Drop or File Dialog will have path converted.
For paths which are already saved in scene please convert them manually.
