### ISSUE TITLE
Object reflection field lose value on script reload

### ISSUE THREAD

**Issue by ducpham-indi** [indigames/igeCreator#30]
Object reflection field lose value on script reload, even if there are no change to reflection fields

**Comment by thai-phi** [comment]
User should save the scene after changed reflection value, before edit the script. The script reload is activated once the script file has changed, so it should reload with the value saved in the scene file.

**Comment by ducpham-indi** [comment]
Reopenning, if the user already save, editing the script still make the reflection reference value

**Comment by thai-phi** [comment]
Fixed in v0.0.6
