### ISSUE TITLE
[Bug] Scene and Game window showcase being scaled

### ISSUE THREAD

**Issue by viet-hoang-96** [indigames/igeCreator#95]
FIXED: Scene scale when place Game Window beside Scene Window and hit Play then Stop, Game Scene has the same problem when Play and change size 
UPDATE: Game window still scale in change window side in this situation (place beside)

**Comment by viet-hoang-96** [comment]
![image](https://user-images.githubusercontent.com/52899605/135020797-d04f3742-9b6e-4988-9b90-fdf677933174.png)

**Comment by viet-hoang-96** [comment]
![image](https://user-images.githubusercontent.com/52899605/135023513-6a1f0f41-35b0-4d84-94fd-813257617fec.png)

**Comment by thai-phi** [comment]
Fixed, checked with build#98.
