### ISSUE TITLE
[Bug] Disable/Enable not working on edit mode (object, component like Figure), should hide Enable option of Transform component

### ISSUE THREAD

**Issue by viet-hoang-96** [indigames/igeCreator#97]
Detail in comment

**Comment by viet-hoang-96** [comment]
![image](https://user-images.githubusercontent.com/52899605/135021917-96227e5b-76b9-441e-8ba9-7361982af0bd.png)

**Comment by viet-hoang-96** [comment]
I disabled floor mesh but it's not working

**Comment by viet-hoang-96** [comment]
![image](https://user-images.githubusercontent.com/52899605/135558190-12840362-07bb-4980-a9e8-b815ce19ffd0.png)
There's one more problem when I disabled the button but the label still display

**Comment by thai-phi** [comment]
Fixed in build#119
